namespace Rant.Arithmetic
{
    internal enum RMathToken
    {
        LeftParen,
        RightParen,
        Equals,
        Plus,
        Minus,
        Asterisk,
        Slash,
        Caret,
        Name,
        Number,
        Increment,
        Decrement,
        Modulo,
        Swap,
        Root,
        AddAssign,
        SubAssign,
        MulAssign,
        DivAssign,
        ModAssign,
        PowAssign,
        RootAssign,
        Pipe,
        End
    }
}